workflows:
  android-debug:
    name: SZXVPN Android Debug

    environment:
      java: 17

    scripts:
      - name: Check project
        script: |
          ls -la
          ls -la app

      - name: Make Gradle executable
        script: |
          chmod +x ./gradlew

      - name: Clean
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/**/*.apk
